---
- name: updating node with ubuntu OS
  hosts: all
  become: yes
  vars:
    user: ubuntu
  tasks:
  - name: update and upgrade repository
    ansible.builtin.apt:
      update_cache: true
      upgrade: yes
      state: latest
- name: install software on node gw
  hosts: 
  - gw
  become: yes
  vars:
    user: ubuntu
  tasks:
  - name: install software
    ansible.builtin.apt:
      pkg:
      - novnc
      - websockify
      - wireguard-tools
- name: install software on lxc
  hosts: 
  - lxc
  become: yes
  vars:
    user: ubuntu
  tasks:
    - name: install software
      ansible.builtin.apt:
        pkg:
        - openvswitch-switch
        - openvswitch-common 
    - name: install lxd
      community.general.snap:
        name:
          - lxd
    - name: create netplan /etc/netplan/02_net.yaml
      ansible.builtin.blockinfile:
        path: /etc/netplan/02_net.yaml
        create: true
        block: |
          network:
            bridges:
              pe1ge0:
                openvswitch: {}
                interfaces:
                - eth1
              pe2ge0:
                openvswitch: {}
                interfaces:
                - eth2
              pe3ge0:
                openvswitch: {}
                interfaces:
                - eth3
              pe4ge0:
                openvswitch: {}
                interfaces:
                - eth4
              pe1ge1:
                openvswitch: {}
                interfaces:
                - eth5
              pe2ge1:
                openvswitch: {}
                interfaces:
                - eth6
              pe3ge1:
                openvswitch: {}
                interfaces:
                - eth7
              pe4ge1:
                openvswitch: {}
                interfaces:
                - eth8
    - name: chmod /etc/netplan/02_net.yaml
      ansible.builtin.file:
        path: /etc/netplan/02_net.yaml
        mode: '0600'
    - name: applying netplan
      ansible.builtin.command: netplan apply
      changed_when: true
- name: install podman and containerd on crpd
  hosts: 
  - crpd
  become: yes
  vars:
    user: ubuntu
  tasks:
    - name: install podman and containerd on node crpd
      ansible.builtin.apt:
        pkg:
        - podman
        - containerd
    - name: upload install_crpd.sh script
      ansible.builtin.blockinfile:
        path: /home/ubuntu/install_crpd.sh
        create: true
        block: |
          #!/usr/bin/env bash
          export NAME=$1
          export VER=$2
          if [ "${NAME}" == "" ];
          then
            echo "variable NAME is not defined"
            exit
          fi
          if [ "${VER}" == "" ];
          then
            echo "variable VER is not defined"
            exit
          fi
          sudo podman volume create ${NAME}-config
          sudo podman volume create ${NAME}-varlog
          sudo podman run --rm --detach --name ${NAME} -h ${NAME} \
                --net=host --privileged \
                -v ${NAME}-config:/config \
                -v ${NAME}-varlog:/var/log \
                -it localhost/crpd:${VER}
    - name: chmod /home/ubuntu/install_crpd.sh
      ansible.builtin.file:
        path: /home/ubuntu/install_crpd.sh
        mode: '0777'
- name: reboot host
  hosts: 
  - nms1
  - nms2
  - lxc
  - crpd
  become: yes
  vars:
    user: ubuntu
  tasks:
  - name: Unconditionally reboot the machine with all defaults
    tags:
      - reboot
    ansible.builtin.reboot:
      msg: "Rebooting machine in 5 seconds"
- name: reboot gw
  hosts: 
  - gw
  become: yes
  vars:
    user: ubuntu
  tasks:
  - name: Unconditionally reboot the machine with all defaults
    tags:
      - reboot
    ansible.builtin.reboot:
      msg: "Rebooting machine in 5 seconds"

