hostname leaf1
user admin group administrators password plaintext pass01
user admin authorized-key ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCrWvRNB9ApfNb5jxQ3B2sfiSu4872YEETtCN8xs8U9u8Ls3eMF0tSCFlgIkrcnph3s4Gn/JDZISfH2/PPXoNkyN7Wl9X5/ZrTMx89lh8ofF8Rj66rxY8eoTKdAFHDdkofR9JJN0EW8pvCROjB3xU0ykBAUZiUBo6vGyKd5vNL4qg8eOglTbPux5cHbOmtJHTDJom+Ye+FNFLscVLgRhCjdau48Cb1ynHvrSEt/b2uRYrAB7E6WC65tJbIO6dGAq4V73WDbuSonBZOnAiPQM46EJNiHMseKKf07VCWwdn2Kly3xJCj02eb1vdejsjqw69lMxZID5+Apcof2Z7q0afb7 user@vmmlab
no ntp enable
ssh server vrf mgmt
vlan 1
interface mgmt
    no shutdown
    ip static 172.16.11.21/24
https-server vrf mgmt
