
[Interface]
PrivateKey=2EoaALNr2kQJcJw3izkLUpUrhPrQvAENpcwehl0D7G8=
Address=192.168.199.0/31,fc00:dead:beef:ffcc::1000:0/127
ListenPort=443
[Peer]
PublicKey=Vu3KP0P1b20Em2MeFqDOkEatBVVB3Pmk9OV+Tnyozg8=
AllowedIPs=192.168.199.1/32,fc00:dead:beef:ffcc::1000:1/128