cat << EOF | sudo tee -a /etc/frr/frr.conf
!
router bgp 4200000200
 no bgp ebgp-requires-policy
 neighbor 192.168.220.0 remote-as 4200000001
 neighbor 192.168.220.0 bfd
 neighbor 192.168.220.0 bfd profile bfd1
 neighbor 192.168.220.2 remote-as 4200000011
 neighbor 192.168.220.2 bfd
 neighbor 192.168.220.2 bfd profile bfd1
 neighbor 192.168.220.4 remote-as 4200000012
 neighbor 192.168.220.4 bfd
 neighbor 192.168.220.4 bfd profile bfd1
 neighbor 192.168.220.6 remote-as 4200000013
 neighbor 192.168.220.6 bfd
 neighbor 192.168.220.6 bfd profile bfd1
 !
 address-family ipv4 unicast
    neighbor 192.168.220.0 activate
    neighbor 192.168.220.2 activate
    neighbor 192.168.220.4 activate
    neighbor 192.168.220.6 activate
 exit-address-family
exit
!
bfd
 profile bfd1
  echo transmit-interval 500
  echo receive-interval 500
 exit
 !
exit
!
end
EOF



sudo sed -i -e "s/bgpd=no/bgpd=yes/" /etc/frr/daemons
sudo sed -i -e "s/bfdd=no/bfdd=yes/" /etc/frr/daemons
sudo systemctl restart frr