vm "r1" {
      hostname "r1";
      basedisk "/vmm/data/base_disks//junos/vsrx//junos-media-srxmr-x86-64-vmdisk-21.1R1.7.vmdk";
      memory 4096;
      ncpus 2;
      interface "vio0" { bridge "external"; };
      //Interface r0-r1 (net-name direct1)
      interface "vio1" { bridge "private1"; };
      VMX_SYSTEST_CONFIG
      setvar "qemu_args" "-cpu qemu64,+vmx,+ssse3,+sse4_1,+sse4_2,+aes,+avx,+pat,+pclmulqdq,+rdtscp,+syscall,+tsc-deadline,+x2apic,+xsave";
   };


   vmm monitor -t <vm name>
 
info network
 
find the link you want to change and then:
 
set_link <nic name> off/on
 
then close the telnet connection (ctrl ]c) - do not type quit or the hypervisor will terminate your vm 
 