system {
    host-name dc1leaf1;
    root-authentication {
        encrypted-password $1$tPid8o5m$iHBIgfer0e3m/PSgES6ci/;
    }
    default-address-selection;
    login {
        user admin {
            class super-user;
            authentication {
                encrypted-password $1$tPid8o5m$iHBIgfer0e3m/PSgES6ci/;
                ssh-rsa "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDC523szGqQMF4/jACq12+VveiQtoz94GJTI3Bit2N0ya6CN+CmJtOW+V0QID1N+Hfh2WgUhKzqRT2YJBboxecYbpdmFfvIrqUpm8mMUhUGdARqKM21dp5g2xlr/3qzadqh29r6z4M8yrr/HPQs9FPKGp9pKpeG26+s3d6RQrmMCWgiVdSiT3eY4vvX5rt9GAdYOxKrw+x7r6R5ubFX/Qk+8PPzqe/9jWH2kUzIVg9iLvtX+qiDM0Fx95QvaZ/MtZd3XDXgxKGQCLCWHHcWXenyaoVDjO/alMNN4JNa+LiQTaWT4H+lDWdOU5/PeX22iejRmfX0SyFL7PLdzKhdxvdJ";
                }
        }
    }
    services {
        ssh {
            root-login allow;
            sftp-server;
        }
        netconf {
            ssh;
        }
    }
    syslog {
        user * {
            any emergency;
        }
        file messages {
            any notice;
            authorization info;
        }
        file interactive-commands {
            interactive-commands any;
        }
    }
    
}
system {
    management-instance;
}

chassis {
    network-services enhanced-ip;
    evpn-vxlan-default-switch-support;
}
interfaces {
   fxp0 {
      unit 0 {
         family inet {
         address 172.16.51.111/24;
         }
      }
    }
}

