system {
    host-name fw2;
    root-authentication {
        encrypted-password $1$iPVtx3Ds$6lkyTFy58bHp5DJreuX1K/;
    }
    default-address-selection;
    login {
        user admin {
            class super-user;
            authentication {
                encrypted-password $1$iPVtx3Ds$6lkyTFy58bHp5DJreuX1K/;
                ssh-rsa "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDC523szGqQMF4/jACq12+VveiQtoz94GJTI3Bit2N0ya6CN+CmJtOW+V0QID1N+Hfh2WgUhKzqRT2YJBboxecYbpdmFfvIrqUpm8mMUhUGdARqKM21dp5g2xlr/3qzadqh29r6z4M8yrr/HPQs9FPKGp9pKpeG26+s3d6RQrmMCWgiVdSiT3eY4vvX5rt9GAdYOxKrw+x7r6R5ubFX/Qk+8PPzqe/9jWH2kUzIVg9iLvtX+qiDM0Fx95QvaZ/MtZd3XDXgxKGQCLCWHHcWXenyaoVDjO/alMNN4JNa+LiQTaWT4H+lDWdOU5/PeX22iejRmfX0SyFL7PLdzKhdxvdJ";
                }
        }
    }
    services {
        ssh {
            root-login allow;
            sftp-server;
        }
        netconf {
            ssh;
        }
    }
    syslog {
        user * {
            any emergency;
        }
        file messages {
            any notice;
            authorization info;
        }
        file interactive-commands {
            interactive-commands any;
        }
    }
    
}
system {
    management-instance;
}

interfaces {
    fxp0 {
        unit 0 {
            family inet {
                address 172.16.52.22/24;
            }
        }
    }   
}
security {
	screen {
        ids-option untrust-screen {
            icmp {
                ping-death;
            }
            ip {
                source-route-option;
                tear-drop;
            }
            tcp {
                syn-flood {
                    alarm-threshold 1024;
                    attack-threshold 200;
                    source-threshold 1024;
                    destination-threshold 2048;
                    timeout 20;
                }
                land;
            }
        }
    }
    policies {
        from-zone trust to-zone trust {
            policy default-permit {
                match {
                    source-address any;
                    destination-address any;
                    application any;
                }
                then {
                    permit;
                }
            }
        }
        from-zone trust to-zone untrust {
            policy default-permit {
                match {
                    source-address any;
                    destination-address any;
                    application any;
                }
                then {
                    permit;
                }
            }
        }   
    }
    zones {
        security-zone trust {
            tcp-rst;
        }
        security-zone untrust {
            screen untrust-screen;
        }
    }
}
interfaces {
ge-0/0/0 {
        unit 0 {
        family inet {
                address 172.16.53.2/24;
                }
        family inet6 {
                address fc00:dead:beef:a063::2/64;
            }
            }
        }
}
