system {
    host-name pe1;
    root-authentication {
        encrypted-password $1$bm2Z0dWd$29nTDL.vWLJqYEcfl/TPo.;
    }
    default-address-selection;
    login {
        user admin {
            class super-user;
            authentication {
                encrypted-password $1$bm2Z0dWd$29nTDL.vWLJqYEcfl/TPo.;
                ssh-rsa "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDC523szGqQMF4/jACq12+VveiQtoz94GJTI3Bit2N0ya6CN+CmJtOW+V0QID1N+Hfh2WgUhKzqRT2YJBboxecYbpdmFfvIrqUpm8mMUhUGdARqKM21dp5g2xlr/3qzadqh29r6z4M8yrr/HPQs9FPKGp9pKpeG26+s3d6RQrmMCWgiVdSiT3eY4vvX5rt9GAdYOxKrw+x7r6R5ubFX/Qk+8PPzqe/9jWH2kUzIVg9iLvtX+qiDM0Fx95QvaZ/MtZd3XDXgxKGQCLCWHHcWXenyaoVDjO/alMNN4JNa+LiQTaWT4H+lDWdOU5/PeX22iejRmfX0SyFL7PLdzKhdxvdJ";
                }
        }
    }
    services {
        ssh {
            root-login allow;
            sftp-server;
        }
        netconf {
            ssh;
        }
    }
    syslog {
        user * {
            any emergency;
        }
        file messages {
            any notice;
            authorization info;
        }
        file interactive-commands {
            interactive-commands any;
        }
    }
    
}
system {
    management-instance;
}

chassis {
    network-services enhanced-ip;
}
interfaces {
   fxp0 {
      unit 0 {
         family inet {
         address 172.16.52.3/24;
         }
      }
    }
}
interfaces {
lo0 {
        unit 0 {
        family inet {
                address 10.100.255.1/32 {
                    primary;
                    preferred;
                }
                }
        family inet6 {
                address fc00:dead:beef:ffff::ffff:1/128;
            }
            family iso {
                address 49.0001.0101.0025.5001.00;
            }
            }
        }
ge-0/0/0 {
        unit 0 {
        family inet {
                address 172.16.54.1/24;
                }
        family inet6 {
                address fc00:dead:beef:a054::1/64;
            }
            }
        }
}
protocols { 
	isis {
                level 2 {
                        authentication-key "$9$H.fQ69A0BE9CK8LxsYTzF/9AtuO1Ec"; ## SECRET-DATA
                        authentication-type md5;
                    }
                        source-packet-routing {
                                srv6 {
                                    locator SRV6-LOC-1 {
                                        end-sid fc00:dead:beef:ff01::;
                                    }
                                }
                            }
                        interface  lo0.0 {
                                    level 1 disable;
                                    passive; 
                                    }
                            }
        }
protocols {
   lldp {
      interface all;
      interface fxp0 {
        disable;
      }
      }
}
routing-options {
    router-id 10.100.255.1;
    route-distinguisher-id 10.100.255.1;
    source-packet-routing {
        srv6 {
            locator SRV6-LOC-1 fc00:dead:beef:ff01::/64;
        }
    }
       
    forwarding-table {
        export LB;
    }
}
policy-options {
    policy-statement LB {
        term 1 {
            then {
                load-balance per-flow;
                accept;
            }
        }
    }
}
