---
- name: change to SR
  hosts:
  - pe
  - p
  connection: local
  gather_facts: no
  vars:
    user: admin
  tasks:
    - name: load pce configuration
      juniper.device.config:  
        template: to_sr.j2
        format: set
        load: merge
        vars: "{{ lookup('file', playbook_dir + '/vars_' + inventory_hostname + '.yaml') | from_yaml}}"
- name: add configuration on p5
  hosts: 
  - p5
  connection: local
  gather_facts: no
  vars:
    user: admin
  tasks:
    - name: load configuration into p5
      juniper.device.config:  
        load: set
        lines:
        - "set protocols mpls traffic-engineering database import l3-unicast-topology bgp-link-state"