vlan 1,21
interface mgmt
    no shutdown
    ip static 172.16.11.4/24
interface lag 1
    no shutdown
    no routing
    vlan trunk native 1
    vlan trunk allowed all
    lacp mode active
interface lag 2
    no shutdown
    no routing
    vlan trunk native 1
    vlan trunk allowed all
    lacp mode active
interface lag 3 multi-chassis
    no shutdown
    no routing
    vlan trunk native 1
    vlan trunk allowed all
    lacp mode active
interface lag 4 multi-chassis
    no shutdown
    no routing
    vlan trunk native 1
    vlan trunk allowed all
    lacp mode active
interface 1/1/3
    no shutdown
    mtu 9000
    lag 1
interface 1/1/4
    no shutdown
    mtu 9000
    lag 1
interface 1/1/5
    no shutdown
    mtu 9000
    lag 2
interface 1/1/6
    no shutdown
    mtu 9000
    lag 2
interface 1/1/7
    no shutdown
    mtu 9000
    lag 3
interface 1/1/8
    no shutdown
    mtu 9000
    lag 4
vsx
    inter-switch-link lag 1
    role secondary
!
!
