set security zones security-zone trust host-inbound-traffic system-services ping
set security zones security-zone trust host-inbound-traffic system-services ssh
set security zones security-zone trust host-inbound-traffic protocols all
set security zones security-zone trust interfaces ge-0/0/1.0
set security zones security-zone trust interfaces ge-0/0/2.0
set security zones security-zone trust interfaces ge-0/0/3.0
set security zones security-zone trust interfaces ge-0/0/4.0
set interfaces ge-0/0/1 mtu 9000
set interfaces ge-0/0/1 unit 0 family inet address 172.16.255.136/31
set interfaces ge-0/0/2 mtu 9000
set interfaces ge-0/0/2 unit 0 family inet address 172.16.255.138/31
set interfaces ge-0/0/3 mtu 9000
set interfaces ge-0/0/3 unit 0 family inet address 172.16.255.140/31
set interfaces ge-0/0/4 mtu 9000
set interfaces ge-0/0/4 unit 0 family inet address 172.16.255.142/31
delete interfaces lo0 
set interfaces lo0 unit 0 family inet address 172.16.255.2/32
set policy-options policy-statement to_bgp_spine term 1 from route-filter 172.16.255.2/32 exact
set policy-options policy-statement to_bgp_spine term 1 then accept
set protocols bgp group to_spine export to_bgp_spine
set protocols bgp group to_spine multipath multiple-as
set protocols bgp group to_spine bfd-liveness-detection minimum-interval 1000
set protocols bgp group to_spine bfd-liveness-detection multiplier 3
set protocols bgp group to_spine neighbor 172.16.255.137 peer-as 4200001001
set protocols bgp group to_spine neighbor 172.16.255.139 peer-as 4200001002
set protocols bgp group to_spine neighbor 172.16.255.141 peer-as 4200001003
set protocols bgp group to_spine neighbor 172.16.255.143 peer-as 4200001004
set routing-options autonomous-system 4200009002
