#include "/vmm/bin/common.defs"
#include "/vmm/data/vmm-configs/common/vmxc/common.vjunos.defs"

#undef vjunos_router_disk
#define vjunos_router_disk basedisk "/vmm/data/user_disks/irzan/images/vJunos-router-26.2R1.7.qcow2";
#undef gw_disk
#define gw_disk basedisk "/vmm/data/user_disks/irzan/images/gw3.qcow2";
#undef ubuntu_disk
#define ubuntu_disk basedisk "/vmm/data/user_disks/irzan/images/ubuntu26.04v2.qcow2";

config "lab3" {

  #undef EM_IPADDR
  #define EM_IPADDR interface "em0" { bridge "mgmt";};
  #undef VJUNOS_CHASSIS_NAME
  #define VJUNOS_CHASSIS_NAME r1
  
  VJUNOS_CHASSIS_START()
  VJUNOS_START(r1, 0)
     setvar "attach_usb" "0";
    VJUNOS_INSTANCE(r1, vjunos_router_disk basedisk, VJUNOS_PRODUCT_VMX, 0)
    VJUNOS_CONNECT(VJUNOS_GE(0, 0, 0), r1ge0)
    VJUNOS_CONNECT(VJUNOS_GE(0, 0, 1), wan1)
    VJUNOS_CONNECT(VJUNOS_GE(0, 0, 2), wan2)
  VJUNOS_END
  VJUNOS_CHASSIS_END

  #undef VJUNOS_CHASSIS_NAME
  #define VJUNOS_CHASSIS_NAME r2
  VJUNOS_CHASSIS_START()
  VJUNOS_START(r2, 0)
     setvar "attach_usb" "0";
    VJUNOS_INSTANCE(r2, vjunos_router_disk basedisk, VJUNOS_PRODUCT_VMX, 0)
    VJUNOS_CONNECT(VJUNOS_GE(0, 0, 0), r2ge0)
    VJUNOS_CONNECT(VJUNOS_GE(0, 0, 1), wan1)
    VJUNOS_CONNECT(VJUNOS_GE(0, 0, 2), wan3)
  VJUNOS_END
  VJUNOS_CHASSIS_END

  #undef VJUNOS_CHASSIS_NAME
  #define VJUNOS_CHASSIS_NAME r3
  VJUNOS_CHASSIS_START()
  VJUNOS_START(r3, 0)
     setvar "attach_usb" "0";
    VJUNOS_INSTANCE(r3, vjunos_router_disk basedisk , VJUNOS_PRODUCT_VMX, 0)
    VJUNOS_CONNECT(VJUNOS_GE(0, 0, 0), r3ge0)
    VJUNOS_CONNECT(VJUNOS_GE(0, 0, 1), wan2)
    VJUNOS_CONNECT(VJUNOS_GE(0, 0, 2), wan4)
  VJUNOS_END
  VJUNOS_CHASSIS_END

  #undef VJUNOS_CHASSIS_NAME
  #define VJUNOS_CHASSIS_NAME r4
  VJUNOS_CHASSIS_START()
  VJUNOS_START(r4, 0)
    setvar "attach_usb" "0";
    VJUNOS_INSTANCE(r4, vjunos_router_disk basedisk, VJUNOS_PRODUCT_VMX, 0)
    VJUNOS_CONNECT(VJUNOS_GE(0, 0, 0), r4ge0)
    VJUNOS_CONNECT(VJUNOS_GE(0, 0, 1), wan3)
    VJUNOS_CONNECT(VJUNOS_GE(0, 0, 2), wan4)
  VJUNOS_END
  VJUNOS_CHASSIS_END

  vm "gw" {
    hostname "gw";
    gw_disk
    ncpus 2;
    memory 4096;
    setvar "+qemu_args" "-cpu qemu64,+vmx";
    setvar "attach_usb" "0";

    interface "em0" { 
        bridge "external"; 
        ext_vlanid 0;
    };
    interface "em1" { 
        bridge "mgmt"; 
        ext_vlanid 0;
    };
  };

  vm "svr1" {
    hostname "svr1";
    ubuntu_disk basedisk
    memory 2048;
    ncpus 1;
    setvar "attach_usb" "0";
    interface "em0" {
      bridge "r1ge0";
      ext_vlanid 0;
    };
  };
  vm "svr2" {
    hostname "svr1";
    ubuntu_disk basedisk
    memory 2048;
    ncpus 1;
    setvar "attach_usb" "0";
    interface "em0" {
      bridge "r2ge0";
      ext_vlanid 0;
    };
  };
  vm "svr3" {
    hostname "svr1";
    ubuntu_disk basedisk
    memory 2048;
    ncpus 1;
    setvar "attach_usb" "0";
    interface "em0" {
      bridge "r3ge0";
      ext_vlanid 0;
    };
  };
  vm "svr4" {
    hostname "svr1";
    ubuntu_disk basedisk
    memory 2048;
    ncpus 1;
    setvar "attach_usb" "0";
    interface "em0" {
      bridge "r4ge0";
      ext_vlanid 0;
    };
  };
    bridge "mgmt" {};
    bridge "r1ge0" {};
    bridge "r2ge0" {};
    bridge "r3ge0" {};
    bridge "r4ge0" {};
    bridge "wan1" {};
    bridge "wan2" {};
    bridge "wan3" {};
    bridge "wan4" {};
};